trigger:
- master

parameters:
- name: appFullName
  type: string
  default: Lance

steps:
- script: echo ${{ parameters.appFullName }}
- template: template.yml
- script: echo ${{ parameters.TestIfOk }}
