trigger:
- master

parameters:
- name: appFullName
  type: string
  default: Lance
- name: TestIfOk
  type: string
  default: OK

steps:
- script: echo ${{ parameters.appFullName }}
- template: template.yml
- script: echo ${{ parameters.TestIfOk }}
