parameters:
- name: detroyresources
  displayName: do you want to destroy the resources?
  type: boolean
  default: false 

trigger:
- main
stages:
- stage: terraform
  displayName: Devo
  variables:
    - group: "Terraform-Group-Variables"
  jobs:
  - ${{ if eq(parameters.detroyresources, false) }}:
    - template: templateapply.yml
      parameters:
        appFullName: Lance
        TestIfOk: OK
        env: dev
  - ${{ if eq(parameters.detroyresources, true) }}:
    - template: templatedestroy.yml
      parameters:
        appFullName: Lance
        TestIfOk: OK
        env: dev
  - template: jobs.yml
      parameters:
        appFullName: Lance
        TestIfOk: OK
        env: dev