trigger:
- main
stages:
- stage: terraform
  displayName: Devo
  variables:
    - group: "Terraform-Group-Variables"
  jobs:
    - template: template.yml
      parameters:
        appFullName: Lance
        TestIfOk: OK
        env: devo
