jobs:
  - deployment: terraformsetup
    displayName: terraform setup
    pool:
      name: testpool 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@0
          - script: |
              echo "terraform setup"
            displayName: 'Install tf packages'