jobs:
  - job: terraform setup
    displayName: terraformsetup
    pool:
      name: testpool 
      vmImage: ubuntu-latest

    steps:
    - script: |
        echo "terraform setup"
      displayName: 'Install tf packages'