jobs:
  - deployment: terraformsetup
    displayName: terraform setup
    environment: ${{parameters.env}}
    pool:
      name: testpool 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: TerraformInstaller@0
          - script: |
              echo "terraform setup"
            displayName: 'Install tf packages'

          - task: TerraformCLI@0
            displayName: 'init'
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendType: 'azurerm'
              backendServiceArm: 'Azure Pass - Sponsorship(31a90186-a097-4b71-9527-2ce644c05cb4)'
              backendAzureRmSubscriptionId: '31a90186-a097-4b71-9527-2ce644c05cb4'
              backendAzureRmResourceGroupName: 'tfstateaccount'
              backendAzureRmStorageAccountName: 'terraformstateall'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev/terraform.tfstate'
              allowTelemetryCollection: true

          - task: TerraformCLI@0
            inputs:
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendType: 'azurerm'
              backendServiceArm: 'Azure Pass - Sponsorship(31a90186-a097-4b71-9527-2ce644c05cb4)'
              backendAzureRmSubscriptionId: '31a90186-a097-4b71-9527-2ce644c05cb4'
              backendAzureRmResourceGroupName: 'tfstateaccount'
              backendAzureRmStorageAccountName: 'terraformstateall'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev/terraform.tfstate'
              allowTelemetryCollection: true
            displayName: 'plan'

          - task: TerraformCLI@0
            inputs:
              command: 'destroy'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendType: 'azurerm'
              backendServiceArm: 'Azure Pass - Sponsorship(31a90186-a097-4b71-9527-2ce644c05cb4)'
              backendAzureRmSubscriptionId: '31a90186-a097-4b71-9527-2ce644c05cb4'
              backendAzureRmResourceGroupName: 'tfstateaccount'
              backendAzureRmStorageAccountName: 'terraformstateall'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev/terraform.tfstate'
              allowTelemetryCollection: true
            displayName: 'destroy'
